<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace>CourseStudio.ProjectionHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" />
    <ProjectReference Include="../CourseStudio.ProjectionHost.Core/CourseStudio.ProjectionHost.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="CourseStudio.ProjectionHost.Core.Tests" />
  </ItemGroup>
</Project>
